version: "3.9"

services:

    product-service:
        image: soen487-project3/product-service
        build: productService
        restart: always
        environment:
            POSTGRES_USER: ${PRODUCT_SERVICE_POSTGRES_USER}
            POSTGRES_PASSWORD: ${PRODUCT_SERVICE_POSTGRES_PASSWORD}
            POSTGRES_DB: ${PRODUCT_SERVICE_POSTGRES_DB}
            POSTGRES_HOST: product-service-database
            POSTGRES_PORT: ${PRODUCT_SERVICE_POSTGRES_PORT}
            PORT: ${PRODUCT_SERVICE_PORT}
        ports:
            - "${PRODUCT_SERVICE_PORT}:${PRODUCT_SERVICE_PORT}"
        networks:
            - gateway-product-service
            - product-service-db

    product-service-database:
        image: postgres:alpine
        restart: always
        environment:
            POSTGRES_USER: ${PRODUCT_SERVICE_POSTGRES_USER}
            POSTGRES_PASSWORD: ${PRODUCT_SERVICE_POSTGRES_PASSWORD}
            POSTGRES_DB: ${PRODUCT_SERVICE_POSTGRES_DB}
        volumes:
            - product-service-database-data:/var/lib/postgresql/data
        networks:
            - product-service-db

    notif-service:
        image: soen487-project3/notif-service
        build: notifService
        restart: always
        environment:
            EMAIL_USER: ${NOTIF_SERVICE_EMAIL_USER}
            EMAIL_PASS: ${NOTIF_SERVICE_EMAIL_PASS}
            POSTGRES_USER: ${NOTIF_SERVICE_POSTGRES_USER}
            POSTGRES_PASSWORD: ${NOTIF_SERVICE_POSTGRES_PASSWORD}
            POSTGRES_NAME: ${NOTIF_SERVICE_POSTGRES_DB}
            POSTGRES_HOST: notif-service-database
            POSTGRES_PORT: ${NOTIF_SERVICE_POSTGRES_PORT}
            PORT: ${NOTIF_SERVICE_PORT}
        ports:
            - "${NOTIF_SERVICE_PORT}:${NOTIF_SERVICE_PORT}"
        networks:
            - broker-notif-service
            - notif-service-db

    notif-service-database:
        image: postgres:alpine
        restart: always
        environment:
            POSTGRES_USER: ${NOTIF_SERVICE_POSTGRES_USER}
            POSTGRES_PASSWORD: ${NOTIF_SERVICE_POSTGRES_PASSWORD}
            POSTGRES_DB: ${NOTIF_SERVICE_POSTGRES_DB}
        volumes:
            - notif-service-database-data:/var/lib/postgresql/data
        networks:
            - notif-service-db
    gateway:
        image: soen487-project3/gateway
        build: gateway
        restart: always
        environment:
            NODE_ENV: production
            FIREBASE_AUTH: ${FIREBASE_AUTH}
        ports:
            - "8080:8080"
        networks:
            - gateway-network

volumes:
    product-service-database-data:
    notif-service-database-data:

networks:
    gateway-product-service:
    product-service-db:
    broker-notif-service:
    notif-service-db:
    gateway-network:
