version: "3.9"

services:

    product-service:
        image: soen487-project3/product-service
        build: productService
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_HOST: ${POSTGRES_HOST}
            POSTGRES_PORT: ${POSTGRES_PORT}
            PORT: ${PRODUCT_SERVICE_PORT}
        ports:
            - "${PRODUCT_SERVICE_PORT}:${PRODUCT_SERVICE_PORT}"
        networks:
            - gateway-product-service
            - product-service-db

    product-service-database:
        image: postgres:alpine
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - product-service-database-data:/var/lib/postgresql/data
        networks:
            - product-service-db

volumes:
    product-service-database-data:

networks:
    gateway-product-service:
    product-service-db:
