version: "3.9"
services:
  notif-service:
    image: soen487-project3/notif-service
    build: notifService
    restart: always
    environment:
      # EMAIL_USER: ${NOTIF_SERVICE_EMAIL_USER}
      # EMAIL_PASS: ${NOTIF_SERVICE_EMAIL_PASS}
      DJANGO_SUPERUSER_PASSWORD: password
      DJANGO_SUPERUSER_EMAIL: test@test.com
      DJANGO_SUPERUSER_USERNAME: philippe
      # POSTGRES_USER: ${NOTIF_SERVICE_POSTGRES_USER}
      # POSTGRES_PASSWORD: ${NOTIF_SERVICE_POSTGRES_PASSWORD}
      # POSTGRES_NAME: ${NOTIF_SERVICE_POSTGRES_DB}
      POSTGRES_HOST: notif-service-database
      # POSTGRES_PORT: ${NOTIF_SERVICE_POSTGRES_PORT}
      PORT: 8000
    ports:
      - "8000:8000"
    networks:
      - notif-service-db

  notif-service-database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - notif-service-database-data:/var/lib/postgresql/data
    networks:
      - notif-service-db

volumes:
  notif-service-database-data:

networks:
  notif-service-db: